#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Instance Visualizer Script."""

import sys
import os

# Add visualizer module path to sys.path
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))

import visualizer.__main__

#main
def main():
    visualizer.__main__.main()

if __name__ == '__main__':
    main()
