#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Instance Visualizer simulator Script."""

import sys
import os

# Add visualizer module path to sys.path
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))

import visualizer.simulator

#main
def main():
    visualizer.simulator.main()

if __name__ == '__main__':
    main()
