#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Instance Generator Script."""

import sys
import os

# Add generator module path to sys.path
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))
# Add libs (submodules) path to sys.path
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../lib'))

from generator.control import Control

def main():
    """Main."""
    Control().run()

if __name__ == '__main__':
    sys.exit(main())
