#+TITLE: ASPRILO Referential Benchmark Sets
#+AUTHOR: Philipp Obermeier
#+INCLUDE: "./conf.org"

* About

  This is the description of the referential benchmark sets of ASPRILO.


* Instance File Naming Convention

  Instances files are named as
  #+BEGIN_SRC shell
  x<X>_y<X>_n<N>_r<R>_s<S>_ps<PS>_pr<PR>_u<U>_o<o>_N<NI>.lp
  #+END_SRC

  where
  - ~<X>~ is the maximum x-dimension
  - ~<Y>~ is the maximum y-dimension
  - ~<N>~ is the number of nodes
  - ~<R>~ is the number of robots
  - ~<S>~ is the number of shelves
  - ~<PS>~ is the number of picking stations
  - ~<PR>~ is the number of products
  - ~<U>~ is the number of product units globally, i.e., total across all products
  - ~<O>~ is the number of orders
  - ~<NI>~ is the instance count number

  Example
  #+BEGIN_SRC shell
  x10_y10_n100_r5_s20_ps5_pr5_u48_o6_N3.lp
  #+END_SRC
  is an instance where
  - ~10~ is the maximum x-dimension
  - ~10~ is the maximum y-dimension
  - ~100~ is the number of nodes
  - ~5~ is the number of robots
  - ~20~ is the number of shelves
  - ~5~ is the number of picking stations
  - ~5~ is the number of products
  - ~48~ is the number of product units globally, i.e., total across all products
  - ~6~ is the number of orders
  - ~3~ is the instance count number


* Generating Benchmark Sets

  The script ~./generator/test_instances.py~ generates a family of categorized instances
  (by repeatedly invoking ~./generator/ig.py~ with different input parameters). Each
  category emphasizes distinct key characteristics typical to the problem. In particular,
  the following categories have been provided:
  - ~standard_cases~: scenarios based on potential real-life settings
  - ~tiny_cases~: extremely tiny toy scenarios
  - ~grid_scaling~: scenarios regarding different sizes of the grid
  - ~shelves_scaling~: scenarios regarding different numbers of shelves
  - ~robots_scaling~: scenarios regarding different numbers of robots
  - ~pickingstations_scaling~: scenarios regarding different numbers of picking stations
  - ~product_units_orders_scaling~: scenarios regarding combinations of different numbers of product units and orders

  For instances, for the category ~standard_cases~, a set of 10 instances can be generated by
  #+BEGIN_SRC shell
    python ./generator/test_instances.py -N 10 -d <DEST>
  #+END_SRC
  where the resulting instances would be save at directory ~<DEST>~. Further, one can split
  instances into warehouse and order related facts via additional command line option ~--split~ as follows
  #+BEGIN_SRC shell
    python ./generator/test_instances.py -N 10 -d <DEST> --split 5 10
  #+END_SRC
  where the first parameter of split specifies the number of warehouses instances (here 5), and the second
  parameter the number of order instances (here 10) per each warehouse instance.
  A precomputed set of the referential instances for invocation
  #+BEGIN_SRC shell
    python ./generator/test_instances.py -N 10 -d <DEST> --split 10 10
  #+END_SRC
  can be found here (TODO!).
