#+TITLE: ASPRILO Visualizer
#+AUTHOR: Philipp Obermeier
#+INCLUDE: "./conf.org"

* About

  This is the user manual of the instance and plan visualizer of [[file:index.org][ASPRILO]].


* Invocation

  The script ~./visualizer/scripts/visualizer~ provides an visualizer with various option, for
  a detailed list invoke
  #+BEGIN_SRC shell
    ./visualizer/scripts/visualizer -h
  #+END_SRC


* Requirements

** Overview

 The visualizer requires the following software installed on your system:

 1. [[http://github.com/potassco/clingo][clingo5]], version 5.3.0 or later
 2. [[http://www.python.org][Python interpreter version 2.7.x]]
 3. [[http://qt-project.org/qt5][Qt5]]
 4. [[http://pyqt.sourceforge.net/Docs/PyQt5/installation.html][PyQt5]], version 5.6 or later


** Building PyQt5 from Source Code

   We assume that python an Qt5 are already installed on your system.

*** SIP Installation

**** Download

     #+BEGIN_SRC shell
       $ wget https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.1/sip-4.19.1.tar.gz
       $ tar -xzvf sip-4.19.1.tar.gz
     #+END_SRC

**** Configuration

     - In case you install sip system-wide, enter:
       #+BEGIN_SRC shell
	 $ cd sip-4.19.1
	 $ python configure.py
       #+END_SRC

     - In case you are using a virtual environment, enter:
       #+BEGIN_SRC shell
	 $ cd sip-4.19.1
	 $ python configure.py --deployment-target=10.12 --destdir=${VIRTUAL_ENV}/lib/python2.7/site-packages --incdir=${VIRTUAL_ENV}/include/python2.7
       #+END_SRC
       Make sure that the environment variable =VIRTUAL_ENV= is set to the path of your virtual python environment.

**** Building and Installation

     #+BEGIN_SRC shell
       $ make
       $ make install
     #+END_SRC

*** PyQt5 Installation

**** Download

     #+BEGIN_SRC shell
       $ wget https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.8.1/PyQt5_gpl-5.8.1.tar.gz
       $ tar -xzvf PyQt5_gpl-5.8.1.tar.gz
     #+END_SRC

**** Configuration

     - In case you install sip system-wide, enter:
       #+BEGIN_SRC shell
	 $ cd PyQt5_gpl-5.8.1
	 $ $ python configure.py --verbose
       #+END_SRC

     - In case you are using a virtual environment, enter:
       #+BEGIN_SRC shell
	 $ cd PyQt5_gpl-5.8.1
	 $ $ python configure.py --sip=${VIRTUAL_ENV}/bin/sip --sip-incdir=${VIRTUAL_ENV}/include/python2.7/ --verbose
       #+END_SRC

     For both cases, make sure that =qmake= is in your path. Alternatively, add
     =--qmake=<path-to-qmake-bin>= as additional argument to the invocation of the =configure.py=
     script above.

**** Building and Installation

       #+BEGIN_SRC shell
	 $ make
	 $ make install
       #+END_SRC
























* Usage

  TODO
